// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqPNC1WC9CORf0aYw81V_VVPkTDsSj0nc',
    appId: '1:529353115383:web:afaecdcb0867622a5db5f2',
    messagingSenderId: '529353115383',
    projectId: 'e3dadkhodam-7c50c',
    authDomain: 'e3dadkhodam-7c50c.firebaseapp.com',
    storageBucket: 'e3dadkhodam-7c50c.appspot.com',
    measurementId: 'G-JKPSNEL1JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3gDjX8zXcdsLTrmXmQRNokwr4oG0gFA',
    appId: '1:529353115383:android:532a0822ca4f70c35db5f2',
    messagingSenderId: '529353115383',
    projectId: 'e3dadkhodam-7c50c',
    storageBucket: 'e3dadkhodam-7c50c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsVXevWOWeZRBMORrJSaeHekdP9oeby2c',
    appId: '1:529353115383:ios:b6214b1028a425fa5db5f2',
    messagingSenderId: '529353115383',
    projectId: 'e3dadkhodam-7c50c',
    storageBucket: 'e3dadkhodam-7c50c.appspot.com',
    iosClientId: '529353115383-223i957dv48isahv0gj2pj0i4klpmbfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.eNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsVXevWOWeZRBMORrJSaeHekdP9oeby2c',
    appId: '1:529353115383:ios:b6214b1028a425fa5db5f2',
    messagingSenderId: '529353115383',
    projectId: 'e3dadkhodam-7c50c',
    storageBucket: 'e3dadkhodam-7c50c.appspot.com',
    iosClientId: '529353115383-223i957dv48isahv0gj2pj0i4klpmbfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.eNote',
  );
}
